/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practica1_estructurasdedatos_primersemestre2015;

import java.applet.AudioClip;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static practica1_estructurasdedatos_primersemestre2015.Practica1_EstructurasDeDatos_PrimerSemestre2015.listaPoZ;

/**
 *
 * @author juanpablo
 */
public class Creación_Plantas extends javax.swing.JFrame {
   Lista_Plantas_Zombies agregar = new  Lista_Plantas_Zombies();  
    public String image="";
   
    public void cargarimagen(String i){
        ImageIcon foto = new ImageIcon(i);
        Icon icono = new ImageIcon(foto.getImage().getScaledInstance( lblImagenPlanta.getWidth(),  lblImagenPlanta.getHeight(), Image.SCALE_DEFAULT));
        lblImagenPlanta.setIcon(icono);
        this.repaint();
    }
    /**
     * Creates new form Creación_Plantas
     */
    
    
    public Creación_Plantas() {
        initComponents();
          ResetearoRecuperarInformacion();
    }
    
    public void ResetearoRecuperarInformacion(){
        //limpiamos todos los combos
        this.comboPuntos.removeAllItems();
        this.comboDefensa.removeAllItems();
        this.comboTipoAtaque.removeAllItems();
        this.txtNombrePlanta.setText("");
                
        //llenamos los combo de puntos de ataque y defensa
        for (int i=1;i<=1000000;i++){
            this.comboPuntos.addItem(i);
            this.comboDefensa.addItem(i);
        }
  
        //Ataques Disponibles
        this.comboTipoAtaque.addItem("Disparo");
        this.comboTipoAtaque.addItem("Golpe");
        
        //limpiamos memoria
        cargarimagen("");
        image="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogoBuscador = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblImagenPlanta = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnRegresarMenu_AgregarPlanta = new javax.swing.JButton();
        comboPuntos = new javax.swing.JComboBox();
        comboDefensa = new javax.swing.JComboBox();
        txtNombrePlanta = new javax.swing.JTextField();
        comboTipoAtaque = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fileImagenPlantas = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(762, 512));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("SEGA LOGO FONT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("IMAGEN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 90, 30);

        jLabel3.setFont(new java.awt.Font("SEGA LOGO FONT", 0, 18)); // NOI18N
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 20, 90, 19);

        jLabel5.setFont(new java.awt.Font("SEGA LOGO FONT", 0, 18)); // NOI18N
        jLabel5.setText("puntos");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 20, 100, 19);

        jLabel6.setFont(new java.awt.Font("SEGA LOGO FONT", 0, 18)); // NOI18N
        jLabel6.setText("ataque");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(400, 20, 110, 19);

        lblImagenPlanta.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(lblImagenPlanta);
        lblImagenPlanta.setBounds(10, 50, 90, 110);

        jLabel7.setFont(new java.awt.Font("SEGA LOGO FONT", 0, 18)); // NOI18N
        jLabel7.setText("defensa");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(560, 20, 120, 19);

        btnRegresarMenu_AgregarPlanta.setFont(new java.awt.Font("Gunslinger", 0, 14)); // NOI18N
        btnRegresarMenu_AgregarPlanta.setText("Agregar Planta y Regresar a Menu");
        btnRegresarMenu_AgregarPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenu_AgregarPlantaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresarMenu_AgregarPlanta);
        btnRegresarMenu_AgregarPlanta.setBounds(10, 420, 270, 23);

        comboPuntos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboPuntos);
        comboPuntos.setBounds(280, 50, 56, 20);

        comboDefensa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboDefensa);
        comboDefensa.setBounds(560, 50, 56, 20);
        getContentPane().add(txtNombrePlanta);
        txtNombrePlanta.setBounds(130, 50, 120, 20);

        comboTipoAtaque.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboTipoAtaque);
        comboTipoAtaque.setBounds(410, 50, 56, 20);

        jButton1.setFont(new java.awt.Font("Broadway", 0, 14)); // NOI18N
        jButton1.setText("Subir Imagen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 320, 180, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/plantss.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 760, 510);

        fileImagenPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileImagenPlantasActionPerformed(evt);
            }
        });
        getContentPane().add(fileImagenPlantas);
        fileImagenPlantas.setBounds(60, 30, 623, 397);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMenu_AgregarPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenu_AgregarPlantaActionPerformed
        // TODO add your handling code here:
               String nombre = this.txtNombrePlanta.getText();
        String puntosA = this.comboPuntos.getSelectedItem().toString();
        String puntosD = this.comboDefensa.getSelectedItem().toString();
        String tipo = this.comboTipoAtaque.getSelectedItem().toString();              
        
        Plantas_Vs_Zombies pozTemp = new Plantas_Vs_Zombies();
        pozTemp.setNombre(nombre);
        pozTemp.setTipo(tipo);
        pozTemp.setPuntosA(puntosA);
        pozTemp.setPuntosD(puntosD);
        pozTemp.setImagen(image);        

       Plantas_Vs_Zombies.Add(pozTemp);

        JOptionPane.showMessageDialog(this,"El numero de criaturas es "+listaPoZ.Length());                               
        
       ResetearoRecuperarInformacion();

        AudioClip sonido;
sonido = java.applet.Applet.newAudioClip(getClass().getResource("/practica1_estructurasdedatos_primersemestre2015/bingo.wav"));
sonido.play();
         Elegir_Bando mostrar = new Elegir_Bando ();
  mostrar.setVisible(true);
    Creación_Plantas.this.dispose();
mostrar.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRegresarMenu_AgregarPlantaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          DialogoBuscador.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fileImagenPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileImagenPlantasActionPerformed
        // TODO add your handling code here:
          JFileChooser seleccionar = (JFileChooser)evt.getSource();
        String command = evt.getActionCommand();
        if (command.equals(JFileChooser.APPROVE_SELECTION)){
            File archivo = seleccionar.getSelectedFile();
            image=archivo.getAbsolutePath();
            cargarimagen(image);
            DialogoBuscador.setVisible(false);
        }else if (command.equals(JFileChooser.CANCEL_SELECTION)){
            cargarimagen("");
            DialogoBuscador.setVisible(false);
        }
    }//GEN-LAST:event_fileImagenPlantasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creación_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creación_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creación_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creación_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creación_Plantas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DialogoBuscador;
    private javax.swing.JButton btnRegresarMenu_AgregarPlanta;
    private javax.swing.JComboBox comboDefensa;
    private javax.swing.JComboBox comboPuntos;
    private javax.swing.JComboBox comboTipoAtaque;
    private javax.swing.JFileChooser fileImagenPlantas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblImagenPlanta;
    private javax.swing.JTextField txtNombrePlanta;
    // End of variables declaration//GEN-END:variables
}
