/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practica1_estructurasdedatos_primersemestre2015;

import java.applet.AudioClip;

/**
 *
 * @author juanpablo
 */
public class Creación_Plantas extends javax.swing.JFrame {

    /**
     * Creates new form Creación_Plantas
     */
    public Creación_Plantas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        btnRegresarMenu_AgregarPlanta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(762, 512));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("SEGA LOGO FONT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("IMAGEN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 90, 30);

        jLabel3.setFont(new java.awt.Font("SEGA LOGO FONT", 0, 18)); // NOI18N
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 20, 90, 19);

        jLabel5.setFont(new java.awt.Font("SEGA LOGO FONT", 0, 18)); // NOI18N
        jLabel5.setText("puntos");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 20, 100, 19);

        jLabel6.setFont(new java.awt.Font("SEGA LOGO FONT", 0, 18)); // NOI18N
        jLabel6.setText("ataque");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(340, 20, 110, 19);

        jLabel7.setFont(new java.awt.Font("SEGA LOGO FONT", 0, 18)); // NOI18N
        jLabel7.setText("defensa");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(450, 20, 120, 19);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disparo", "Directo", " ", " " }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(340, 50, 80, 20);

        btnRegresarMenu_AgregarPlanta.setFont(new java.awt.Font("Gunslinger", 0, 14)); // NOI18N
        btnRegresarMenu_AgregarPlanta.setText("Agregar Planta y Regresar a Menu");
        btnRegresarMenu_AgregarPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenu_AgregarPlantaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresarMenu_AgregarPlanta);
        btnRegresarMenu_AgregarPlanta.setBounds(250, 450, 270, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/plantss.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 760, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMenu_AgregarPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenu_AgregarPlantaActionPerformed
        // TODO add your handling code here:
        AudioClip sonido;
sonido = java.applet.Applet.newAudioClip(getClass().getResource("/practica1_estructurasdedatos_primersemestre2015/bingo.wav"));
sonido.play();
         Elegir_Bando mostrar = new Elegir_Bando ();
  mostrar.setVisible(true);
    Creación_Plantas.this.dispose();
mostrar.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRegresarMenu_AgregarPlantaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creación_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creación_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creación_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creación_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creación_Plantas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresarMenu_AgregarPlanta;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
