/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practica1_estructurasdedatos_primersemestre2015;

import java.applet.AudioClip;

/**
 *
 * @author juanpablo
 */
public class Elegir_Bando extends javax.swing.JFrame {

    /**
     * Creates new form Elegir_Bando
     */
    Reproductor Music = new Reproductor();
    public Elegir_Bando() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearPlantas = new javax.swing.JButton();
        btnCrearZombies = new javax.swing.JButton();
        btnJuego = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(711, 423));
        setResizable(false);
        getContentPane().setLayout(null);

        btnCrearPlantas.setBackground(new java.awt.Color(102, 255, 51));
        btnCrearPlantas.setForeground(new java.awt.Color(51, 0, 51));
        btnCrearPlantas.setText("Jugador Plantas");
        btnCrearPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPlantasActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearPlantas);
        btnCrearPlantas.setBounds(140, 150, 170, 23);

        btnCrearZombies.setBackground(new java.awt.Color(0, 0, 255));
        btnCrearZombies.setText("Jugador Zombies");
        btnCrearZombies.setPreferredSize(new java.awt.Dimension(711, 423));
        btnCrearZombies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearZombiesActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearZombies);
        btnCrearZombies.setBounds(510, 120, 180, 20);

        btnJuego.setBackground(new java.awt.Color(51, 0, 51));
        btnJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vs.png"))); // NOI18N
        btnJuego.setText("Comenzar Juego");
        btnJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuegoActionPerformed(evt);
            }
        });
        getContentPane().add(btnJuego);
        btnJuego.setBounds(150, 190, 160, 100);

        btnEliminar.setBackground(new java.awt.Color(255, 255, 51));
        btnEliminar.setText("Eliminar Datos");
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(520, 170, 150, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/contra.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 710, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPlantasActionPerformed
        // TODO add your handling code here:
        AudioClip sonido;
sonido = java.applet.Applet.newAudioClip(getClass().getResource("/practica1_estructurasdedatos_primersemestre2015/yoshi.wav"));
sonido.play();

 Usuario_Plantas mostrar = new Usuario_Plantas ();
  mostrar.setVisible(true);
  Elegir_Bando.this.dispose();
mostrar.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCrearPlantasActionPerformed

    private void btnCrearZombiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearZombiesActionPerformed
        // TODO add your handling code here:
             AudioClip sonido;
sonido = java.applet.Applet.newAudioClip(getClass().getResource("/practica1_estructurasdedatos_primersemestre2015/mummy.wav"));
sonido.play();

 Usuario_Zombies mostrar = new Usuario_Zombies ();
  mostrar.setVisible(true);
    Elegir_Bando.this.dispose();
mostrar.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCrearZombiesActionPerformed

    private void btnJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuegoActionPerformed
        // TODO add your handling code here:
        
                     AudioClip sonido;
sonido = java.applet.Applet.newAudioClip(getClass().getResource("/practica1_estructurasdedatos_primersemestre2015/fight.wav"));
sonido.play();



 PlantasVsZombies mostrar = new PlantasVsZombies ();
  mostrar.setVisible(true);
    Elegir_Bando.this.dispose();
mostrar.setLocationRelativeTo(null);

 
    }//GEN-LAST:event_btnJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Elegir_Bando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Elegir_Bando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Elegir_Bando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Elegir_Bando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Elegir_Bando().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearPlantas;
    private javax.swing.JButton btnCrearZombies;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnJuego;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
