/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practica1_estructurasdedatos_primersemestre2015;

import java.applet.AudioClip;
import javax.swing.JOptionPane;
import static practica1_estructurasdedatos_primersemestre2015.Practica1_EstructurasDeDatos_PrimerSemestre2015.listaJ;

/**
 *
 * @author juanpablo
 */
public class Usuario_Plantas extends javax.swing.JFrame {

    /**
     * Creates new form Plantas
     */
    public Usuario_Plantas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombrePlanta = new javax.swing.JTextField();
        txtCantidadPlanta = new javax.swing.JTextField();
        btnAgregarCampos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(595, 382));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setText("Jugador Plantas");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 30, 77, 14);

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 80, 37, 14);

        jLabel4.setText("Cantidad");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 130, 43, 14);
        getContentPane().add(txtNombrePlanta);
        txtNombrePlanta.setBounds(330, 80, 110, 20);
        getContentPane().add(txtCantidadPlanta);
        txtCantidadPlanta.setBounds(330, 130, 110, 20);

        btnAgregarCampos.setText("Agregar más  campos");
        btnAgregarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCamposActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarCampos);
        btnAgregarCampos.setBounds(210, 200, 180, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jug.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCamposActionPerformed
        // TODO add your handling code here:
        
        JugadorGeneral jTemp = new  JugadorGeneral();
        jTemp.setNombre(this.txtNombrePlanta.getText());
        jTemp.setUsuario(this.txtCantidadPlanta.getText());
        
        listaJ.Add(jTemp);        

        JOptionPane.showMessageDialog(this,"Número de Jugador de Plantas es "+listaJ.Length());  
        
        this.txtNombrePlanta.setText("");
        this.txtCantidadPlanta.setText("");
        
        
        
        
        AudioClip sonido;
sonido = java.applet.Applet.newAudioClip(getClass().getResource("/practica1_estructurasdedatos_primersemestre2015/ok.wav"));
sonido.play();
       Creación_Plantas mostrar = new Creación_Plantas ();
mostrar.setVisible(true);
Usuario_Plantas.this.dispose();
mostrar.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAgregarCamposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario_Plantas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCampos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCantidadPlanta;
    private javax.swing.JTextField txtNombrePlanta;
    // End of variables declaration//GEN-END:variables
}
